### ISSUE TITLE
Would you like the debounce-stream module name?

### ISSUE THREAD

**Issue by RangerMauve** [fardog/stream-debounce#2]
I came across this, and it seems to be a lot better than my [debounce-stream](https://github.com/RangerMauve/debounce-stream) module. Would you be interested in taking its name?

**Comment by fardog** [comment]
That's really generous of you! It's true that `debounce-stream` was the original name that I wanted for this module; if you aren't intending to continue maintaining yours, I would take over the name for this module.

I really appreciate it. If you add me as an owner on that module, I can deprecate it and republish stream-debounce on there. Thanks!

**Comment by fardog** [comment]
@RangerMauve forgot to mention; i'll make sure to bump the module version to 2.0.0 before publishing, so anyone that depends on your version won't end up with any issues.

**Comment by RangerMauve** [comment]
Perfect! I've added you as an owner on npm. I'll remove myself when you're all set up. :D

**Comment by fardog** [comment]
@RangerMauve thanks! It's been published. Aside from some weird issues that travis is having with the module rename all else seems good to go!

**Comment by RangerMauve** [comment]
Cool. I'll mark my repo as deprecated in the meantime.
